// Code generated by "stringer -type=LogLevel"; DO NOT EDIT.

package bbb

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LogLevelNone-1]
	_ = x[LogLevelError-2]
	_ = x[LogLevelWarning-3]
	_ = x[LogLevelDefault-4]
	_ = x[LogLevelVerbose-5]
}

const _LogLevel_name = "LogLevelNoneLogLevelErrorLogLevelWarningLogLevelDefaultLogLevelVerbose"

var _LogLevel_index = [...]uint8{0, 12, 25, 40, 55, 70}

func (i LogLevel) String() string {
	i -= 1
	if i < 0 || i >= LogLevel(len(_LogLevel_index)-1) {
		return "LogLevel(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _LogLevel_name[_LogLevel_index[i]:_LogLevel_index[i+1]]
}
